name: "Close stale PRs"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: "This PR is stale because it has been open 3 months with no activity. Remove stale label or comment or this will be closed in 3 months."
          close-pr-message: "This PR was closed because it has been stalled for 3 months with no activity."
          days-before-pr-stale: 90
          days-before-pr-close: 90
